# Generated by Django 4.2.11 on 2024-04-16 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='_total',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 13, 36, 50, 5948), verbose_name='Fecha'),
        ),
    ]
