# Generated by Django 4.2.11 on 2024-04-16 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivered',
            field=models.BooleanField(default=True, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 11, 55, 731355), verbose_name='Fecha'),
        ),
    ]
