# Generated by Django 4.2.11 on 2024-05-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_saledetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total cobrado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
