# Generated by Django 4.2.11 on 2024-05-27 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_sale_total_charged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='delivered',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_bakery',
            field=models.BooleanField(db_index=True, default=False, help_text='Si es venta de panaderia, el precio a utilizar es el de mayorista.', verbose_name='Venta de panaderia'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta de Debito/Credito'), ('QR', 'QR')], db_index=True, default='Efectivo', max_length=14, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
