# Generated by Django 4.2.11 on 2024-06-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedaccesstoken'),
        ('users', '0003_create_groups'),
    ]

    operations = [
    ]
