# Generated by Django 4.2.11 on 2024-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
