# Generated by Django 4.2.11 on 2024-04-15 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wholesale',
            field=models.BooleanField(default=False, verbose_name='Venta mayorista'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 17, 2, 34, 55117), verbose_name='Fecha'),
        ),
    ]
