# Generated by Django 4.2.11 on 2024-04-15 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_order_wholesale_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 19, 8, 58, 369109), verbose_name='Fecha'),
        ),
    ]
