# Generated by Django 4.2.11 on 2024-04-16 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_remove_order_payment_method_remove_order_wholesale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 9, 58, 44, 466248), verbose_name='Fecha'),
        ),
    ]
