# Generated by Django 4.2.11 on 2024-04-16 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_order_description_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 10, 38, 33, 844842), verbose_name='Fecha'),
        ),
    ]
