# Generated by Django 4.2.11 on 2024-04-16 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 13, 36, 50, 7626), verbose_name='Fecha'),
        ),
    ]
