# Generated by Django 4.2.11 on 2024-04-16 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 22, 11, 55, 733029, tzinfo=datetime.timezone.utc), verbose_name='Fecha'),
        ),
    ]
