# Generated by Django 4.2.11 on 2024-06-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_alter_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
