# Generated by Django 4.2.11 on 2024-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_code_alter_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='price',
            new_name='public_price',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='wholesale',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
