# Generated by Django 4.2.11 on 2024-04-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_price_pricehistory_public_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='date_updated',
        ),
    ]
