# Generated by Django 4.2.11 on 2024-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
