# Generated by Django 4.2.11 on 2024-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Stock actual'),
        ),
    ]
